.version: &version "15.3.1-dev.fred-staging.1"

apiVersion: v2
name: teleport-plugin-slack
description: A Helm chart for the Teleport Slack Plugin
type: application
version: *version
appVersion: *version
