.version: &version "14.0.0-dev.fred.updater-nonmajor-7"

apiVersion: v2
name: teleport-plugin-discord
description: A Helm chart for the Teleport Discord Plugin
type: application
version: *version
appVersion: *version
