.version: &version "15.2.6-cloud.zac.2"

apiVersion: v2
name: teleport-plugin-discord
description: A Helm chart for the Teleport Discord Plugin
type: application
version: *version
appVersion: *version
