[workspace]
resolver = "2"
members = [
    "lib/srv/desktop/rdp/rdpclient",
    "web/packages/teleport/src/ironrdp"
]

[workspace.package]
edition = "2021"
license = "AGPL-3.0-only"
homepage = "https://github.com/gravitational/teleport"
repository = "https://github.com/gravitational/teleport"
publish = false

[profile.dev]
debug = 1
lto = "off"

[profile.release]
debug = 1
codegen-units = 1

[workspace.dependencies]
# Note: To use a local IronRDP repository as a crate (for example, ironrdp-cliprdr), define the dependency as follows:
# ironrdp-cliprdr = { path = "/path/to/local/IronRDP/crates/ironrdp-cliprdr" }
# TODO: this rev should not be checked in, we should wait for https://github.com/Devolutions/IronRDP/pull/388 to land
ironrdp-cliprdr = { git = "https://github.com/Devolutions/IronRDP", rev = "b70dc2fbea780b1266e1d0d19adb67ffc289073b" }
ironrdp-connector = { git = "https://github.com/Devolutions/IronRDP", rev = "b70dc2fbea780b1266e1d0d19adb67ffc289073b" }
ironrdp-graphics = { git = "https://github.com/Devolutions/IronRDP", rev = "b70dc2fbea780b1266e1d0d19adb67ffc289073b" }
ironrdp-pdu = { git = "https://github.com/Devolutions/IronRDP", rev = "b70dc2fbea780b1266e1d0d19adb67ffc289073b" }
ironrdp-rdpdr = { git = "https://github.com/Devolutions/IronRDP", rev = "b70dc2fbea780b1266e1d0d19adb67ffc289073b" }
ironrdp-rdpsnd = { git = "https://github.com/Devolutions/IronRDP", rev = "b70dc2fbea780b1266e1d0d19adb67ffc289073b" }
ironrdp-session = { git = "https://github.com/Devolutions/IronRDP", rev = "b70dc2fbea780b1266e1d0d19adb67ffc289073b" }
ironrdp-svc = { git = "https://github.com/Devolutions/IronRDP", rev = "b70dc2fbea780b1266e1d0d19adb67ffc289073b" }
ironrdp-tls = { git = "https://github.com/Devolutions/IronRDP", rev = "b70dc2fbea780b1266e1d0d19adb67ffc289073b", features = ["rustls"]}
ironrdp-tokio = { git = "https://github.com/Devolutions/IronRDP", rev = "b70dc2fbea780b1266e1d0d19adb67ffc289073b" }
