[workspace]
resolver = "2"
members = [
    "lib/srv/desktop/rdp/rdpclient",
    "web/packages/teleport/src/ironrdp"
]

[workspace.package]
edition = "2021"
license = "AGPL-3.0-only"
homepage = "https://github.com/gravitational/teleport"
repository = "https://github.com/gravitational/teleport"
publish = false

[profile.dev]
debug = 1
lto = "off"

[profile.release]
debug = 1
codegen-units = 1

[workspace.dependencies]
# Note: To use a local IronRDP repository as a crate (for example, ironrdp-cliprdr), define the dependency as follows:
# ironrdp-cliprdr = { path = "/path/to/local/IronRDP/crates/ironrdp-cliprdr" }
ironrdp-cliprdr = { git = "https://github.com/Devolutions/IronRDP", rev = "685d168f7b5dcc57d097b6fed88668091c1bcd00" }
ironrdp-connector = { git = "https://github.com/Devolutions/IronRDP", rev = "685d168f7b5dcc57d097b6fed88668091c1bcd00" }
ironrdp-graphics = { git = "https://github.com/Devolutions/IronRDP", rev = "685d168f7b5dcc57d097b6fed88668091c1bcd00" }
ironrdp-pdu = { git = "https://github.com/Devolutions/IronRDP", rev = "685d168f7b5dcc57d097b6fed88668091c1bcd00" }
ironrdp-rdpdr = { git = "https://github.com/Devolutions/IronRDP", rev = "685d168f7b5dcc57d097b6fed88668091c1bcd00" }
ironrdp-rdpsnd = { git = "https://github.com/Devolutions/IronRDP", rev = "685d168f7b5dcc57d097b6fed88668091c1bcd00" }
ironrdp-session = { git = "https://github.com/Devolutions/IronRDP", rev = "685d168f7b5dcc57d097b6fed88668091c1bcd00" }
ironrdp-server = { git = "https://github.com/Devolutions/IronRDP", rev = "685d168f7b5dcc57d097b6fed88668091c1bcd00" }
ironrdp-svc = { git = "https://github.com/Devolutions/IronRDP", rev = "685d168f7b5dcc57d097b6fed88668091c1bcd00" }
ironrdp-tls = { git = "https://github.com/Devolutions/IronRDP", rev = "685d168f7b5dcc57d097b6fed88668091c1bcd00", features = ["rustls"]}
ironrdp-tokio = { git = "https://github.com/Devolutions/IronRDP", rev = "685d168f7b5dcc57d097b6fed88668091c1bcd00" }

# ironrdp-cliprdr = { path = "../IronRDP/crates/ironrdp-cliprdr" }
# ironrdp-connector = { path = "../IronRDP/crates/ironrdp-connector" }
# ironrdp-graphics = { path = "../IronRDP/crates/ironrdp-graphics" }
# ironrdp-pdu = { path = "../IronRDP/crates/ironrdp-pdu" }
# ironrdp-rdpdr = { path = "../IronRDP/crates/ironrdp-rdpdr" }
# ironrdp-rdpsnd = { path = "../IronRDP/crates/ironrdp-rdpsnd" }
# ironrdp-session = { path = "../IronRDP/crates/ironrdp-session" }
# ironrdp-server = { path = "../IronRDP/crates/ironrdp-server" }
# ironrdp-svc = { path = "../IronRDP/crates/ironrdp-svc" }
# ironrdp-tls = { path = "../IronRDP/crates/ironrdp-tls", features = ["rustls"]}
# ironrdp-tokio = { path = "../IronRDP/crates/ironrdp-tokio" }
