[workspace]
resolver = "2"
members = [
    "lib/srv/desktop/rdp/rdpclient",
    "web/packages/teleport/src/ironrdp"
]

[workspace.package]
edition = "2021"
license = "AGPL-3.0-only"
homepage = "https://github.com/gravitational/teleport"
repository = "https://github.com/gravitational/teleport"
publish = false

[profile.dev]
debug = 1
lto = "off"

[profile.release]
debug = 1
codegen-units = 1

[workspace.dependencies]
# Note: To use a local IronRDP repository as a crate (for example, ironrdp-cliprdr), define the dependency as follows:
# ironrdp-cliprdr = { path = "/path/to/local/IronRDP/crates/ironrdp-cliprdr" }
# TODO: this rev hash is temporary, change once https://github.com/Devolutions/IronRDP/pull/424 is merged.
ironrdp-cliprdr = { git = "https://github.com/Devolutions/IronRDP", rev = "94c176bf6a9bf0288c5943a607f1f8c6e35fc18c" }
ironrdp-connector = { git = "https://github.com/Devolutions/IronRDP", rev = "94c176bf6a9bf0288c5943a607f1f8c6e35fc18c" }
ironrdp-displaycontrol = { git = "https://github.com/Devolutions/IronRDP", rev = "94c176bf6a9bf0288c5943a607f1f8c6e35fc18c" }
ironrdp-dvc = { git = "https://github.com/Devolutions/IronRDP", rev = "94c176bf6a9bf0288c5943a607f1f8c6e35fc18c" }
ironrdp-graphics = { git = "https://github.com/Devolutions/IronRDP", rev = "94c176bf6a9bf0288c5943a607f1f8c6e35fc18c" }
ironrdp-pdu = { git = "https://github.com/Devolutions/IronRDP", rev = "94c176bf6a9bf0288c5943a607f1f8c6e35fc18c" }
ironrdp-rdpdr = { git = "https://github.com/Devolutions/IronRDP", rev = "94c176bf6a9bf0288c5943a607f1f8c6e35fc18c" }
ironrdp-rdpsnd = { git = "https://github.com/Devolutions/IronRDP", rev = "94c176bf6a9bf0288c5943a607f1f8c6e35fc18c" }
ironrdp-session = { git = "https://github.com/Devolutions/IronRDP", rev = "94c176bf6a9bf0288c5943a607f1f8c6e35fc18c" }
ironrdp-svc = { git = "https://github.com/Devolutions/IronRDP", rev = "94c176bf6a9bf0288c5943a607f1f8c6e35fc18c" }
ironrdp-tls = { git = "https://github.com/Devolutions/IronRDP", rev = "94c176bf6a9bf0288c5943a607f1f8c6e35fc18c", features = ["rustls"]}
ironrdp-tokio = { git = "https://github.com/Devolutions/IronRDP", rev = "94c176bf6a9bf0288c5943a607f1f8c6e35fc18c" }
