.version: &version "14.0.0-dev.noah.745e8be7a924468e83e6a345858af3a83f73caad"

name: teleport-operator
apiVersion: v2
version: *version
appVersion: *version
description: Teleport Operator provides management of select Teleport resources.
icon: https://goteleport.com/images/logos/logo-teleport-square.svg
keywords:
  - Teleport
