name: teleport-cluster
apiVersion: v2
version: "9.1.1-dev.vitor"
appVersion: "9.1.1-dev.vitor"
description: Teleport is a unified access plane for your infrastructure
icon: https://goteleport.com/images/logos/logo-teleport-square.svg
keywords:
  - Teleport
