.version: &version "13.4.11-dev-camh.2"

name: teleport-cluster
apiVersion: v2
version: *version
appVersion: *version
description: Teleport is an access platform for your infrastructure
icon: https://goteleport.com/images/logos/logo-teleport-square.svg
keywords:
  - Teleport

dependencies:
  - name: teleport-operator
    version: *version
    condition: installCRDs,operator.enabled
