.version: &version "13.0.0-tcsc.gha+01"

name: teleport-cluster
apiVersion: v2
version: *version
appVersion: *version
description: Teleport is a unified access plane for your infrastructure
icon: https://goteleport.com/images/logos/logo-teleport-square.svg
keywords:
  - Teleport

dependencies:
  - name: teleport-operator
    version: *version
    condition: installCRDs,operator.enabled