extends: existence
scope:
  - heading
  - table
  - list
  - paragraph
message: "Capitalize the names of Teleport services (%s is incorrect). See the Core Concepts page (https://goteleport.com/docs/core-concepts/) for service names."
level: error
ignorecase: false
tokens:
  - machine id
  - db service
  - '[Dd]atabase service'
  - '[Aa]pp(lication) service'
  - '[Dd]esktop service'
  - '[kK]ubernetes service'
  - '(SSH|ssh) service'
  - '[dD]iscovery service'
  - '[Aa]uth service'
  # Allow for mentions of a local proxy service, but not "proxy service".
  - '(?<!local )[pP]roxy service'
