.version: &version "14.0.0-dev.fred.updater-nonmajor-7"

apiVersion: v2
name: teleport-plugin-jira
description: A Helm chart for the Teleport Jira Plugin
type: application
version: *version
appVersion: *version
