extends: script
level: error
message: "Do not include a Tabs component within a TabItem, as it creates a poor user experience. Instead, provide a single happy path that satisfies most users and separeate other possible ways of doing things into another part of the page (or a separate page). Alternatively, find a way to consolidate the TabItems."
scope: raw
script: |
  text := import("text")
  lines := text.split(scope, "\n")
  getMatches := func() {
    inTabItem := false
    offset := 0
    for l in lines {
      if !inTabItem && text.re_match(`^\s*<TabItem`, l) {
        inTabItem = true
      }
  
      if inTabItem && text.re_match(`^\s*</TabItem`, l) {
        inTabItem = false
      }
  
      if inTabItem && text.re_match(`^\s*<Tabs`, l) {
        return [{
          begin: offset,
          end: offset+len(l)
        }]
      }
      // Advance the offset by the length of the line plus the "\n" char.
      offset += len(l)+1
    }
  }
      
  matches := getMatches()

