extends: script
level: error
message: "Do not include a Tabs component within a TabItem, as it creates a poor user experience. Instead, provide a single happy path that satisfies most users and separeate other possible ways of doing things into another part of the page (or a separate page). Alternatively, find a way to consolidate the TabItems."
scope: raw
script: |
  text := import("text")
  fmt := import("fmt")
  lines := text.re_find(`[^\n]*\n`, scope, -1)
  getMatches := func() {
    inTabItem := false
    offset := 0
    for n, l in lines {
      line := l[0].text
      if !inTabItem && text.re_match(`^\s*<TabItem`, line) {
        fmt.println(line)
        inTabItem = true
      }
  
      if inTabItem && text.re_match(`^\s*</TabItem`, line) {
        fmt.println(line)
        inTabItem = false
      }
  
      if inTabItem && text.re_match(`^\s*<Tabs`, line) {
        fmt.println("bad line:", n, line, l)
        fmt.println(scope[l[0].begin:l[0].end])
        return [{
          begin: l[0].begin,
          end: l[0].end
        }]
      }
    }
  }
      
  matches := getMatches()

