{{ if .Values.operator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
rules:
- apiGroups:
  - "resources.teleport.dev"
  resources:
  - teleportroles
  - teleportroles/status
  - teleportusers
  - teleportusers/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - create
  - get
  - update

- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
{{ end }}
