.version: &version "14.0.0-dev.noah.745e8be7a924468e83e6a345858af3a83f73caad"

name: teleport-kube-agent
apiVersion: v2
version: *version
appVersion: *version
description: Teleport provides a secure SSH, Kubernetes, database and application remote access solution that doesn't get in the way.
icon: https://goteleport.com/images/logos/logo-teleport-square.svg
keywords:
  - Teleport
