extends: substitution
message: Use the verb phrase "%s" instead of "%s", which is the noun form.
ignorecase: true
swap:
  - 'setup (?=\w+)': "set up"
  - 'login (?=\w+)': "log in"
  - 'rollout (?=\w+)': "roll out"
