extends: substitution
message: Use the verb phrase "%s" instead of "%s", which is the noun form.
ignorecase: true
swap:
  - 'setup (?=the |a )': "set up"
  - 'login (?=to )': "log in"
  - 'rollout (?=the |a )': "roll out"
