.version: &version "14.0.0-dev.fred.updater-nonmajor-7"

apiVersion: v2
name: teleport-plugin-msteams
description: A Helm chart for the Teleport MsTeams Plugin
type: application
version: *version
appVersion: *version
