.version: &version "15.3.2-dev-okta-scim.1"

apiVersion: v2
name: teleport-plugin-msteams
description: A Helm chart for the Teleport MsTeams Plugin
type: application
version: *version
appVersion: *version
