.version: &version "15.2.6-cloud.igs.1"

apiVersion: v2
name: teleport-plugin-msteams
description: A Helm chart for the Teleport MsTeams Plugin
type: application
version: *version
appVersion: *version
