.version: &version "15.2.6-cloud.igs.1"

apiVersion: v2
name: teleport-plugin-mattermost
description: A Helm chart for the Teleport Mattermost Plugin
type: application
version: *version
appVersion: *version
