timeout: 20m

options:
  machineType: 'E2_HIGHCPU_32'
  
steps:
  # Run the unit tests. Actual content of this job depends on the changes 
  # detected in the PR
  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-root:teleport7-v0.1.0
    id: run-tests
    dir: /workspace/.cloudbuild/scripts
    entrypoint: bash 
    args: 
      - -c
      - go run ./cmd/unit-tests -w=/workspace -t=$_BASE_BRANCH -c=HEAD
    timeout: 15m
