name: Lint (Docs)
run-name: Lint (Docs)
on:
  pull_request:
    paths:
      - 'docs/**'
      - 'examples/**'
  merge_group:
    paths:
      - 'docs/**'
      - 'examples/**'

jobs:
  doc-tests:
    name: Lint (Docs)
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: "gravitational/docs"
          path: "docs"

      - name: Prepare docs site configuration
        # The environment we use for linting the docs differs from the one we
        # use for the live docs site in that we only test a single version of
        # the content.
        #
        # To do this, we replace the three submodules we use for building the
        # live docs site with a single submodule, pointing to the
        # gravitational/teleport branch we are linting.
        #
        # The docs engine expects a config.json file at the root of the
        # gravitational/docs clone that associates directories with git
        # submodules. By default, these directories represent versioned branches
        # of gravitational/teleport. We override this in order to build only a
        # single version of the docs.
        run: |
          cd $GITHUB_WORKSPACE/docs
          echo "Current system: $(uname -a)"
          echo "pwd after first cd: $(pwd)"
          echo "GitHub workspace: $GITHUB_WORKSPACE"
          echo "" > .gitmodules
          echo -e "cat .gitmodules: \n$(cat .gitmodules)"
          rm -rf content/*
          git submodule add --force -b $GITHUB_HEAD_REF https://github.com/gravitational/teleport -- ./content/docs
          echo "{\"versions\": [{\"name\": \"docs\", \"branch\": \"$GITHUB_HEAD_REF\", \"deprecated\": false}]}" > $GITHUB_WORKSPACE/docs/config.json
          cd $GITHUB_WORKSPACE/docs
          yarn install

      - name: Check spelling
        run: cd $GITHUB_WORKSPACE/docs && yarn spellcheck content/docs

      - name: Lint the docs
        run: cd $GITHUB_WORKSPACE/docs && yarn markdown-lint

      - name: Test the docs build
        run: cd $GITHUB_WORKSPACE/docs && yarn install && yarn build
