# TODO(zmb3): remove this workflow completely after it is no longer
# marked as a required check
name: Lint (Go)
run-name: make lint
on:
  pull_request:
  merge_group:

jobs:
  lint:
    name: no-op
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: |
          echo "Linting for web has been moved to the lint-all workflow"
