name: OS Compatibility Test
run-name: OS Compatibility Test
on:
  pull_request:
  merge_group:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      this-workflow: ${{ steps.changes.outputs.this-workflow }}
      binary-sources: ${{ steps.changes.outputs.binary-sources }}
    steps:
    - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
      id: changes
      with:
        filters: |
          this-workflow:
            - '.github/workflows/os-compatibility-test.yaml'
          binary-sources:
            - '**/*.c'
            - '**/*.go'
            - '**/go.mod'
            - '**/go.sum'
            - '**/Makefile'
            - '**/*.mk'

  build:
    name: OS Compatibility Build
    needs: changes
    if: ${{ needs.changes.outputs.this-workflow == 'true' || (needs.changes.outputs.binary-sources == 'true' && !startsWith(github.head_ref, 'dependabot/'))  }}
    runs-on: ubuntu-22.04-16core

    permissions:
      contents: read

    container:
      image: ghcr.io/gravitational/teleport-buildbox-centos7:teleport15-amd64
      env:
        GOCACHE: /tmp/gocache
        WEBASSETS_SKIP_BUILD: 1

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v4

      - name: Prepare workspace
        uses: ./.github/actions/prepare-workspace

      - name: Run make
        run: |
          make -j"$(nproc)" binaries

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ github.workspace }}/build/

  test-compat:
    needs: build
    name: OS Compatibility Test
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ${{ github.workspace }}/build

      - name: chmod +x
        run: chmod +x ${GITHUB_WORKSPACE}/build/*

      - name: Run compat matrix
        timeout-minutes: 10
        run: |
          cd ${GITHUB_WORKSPACE} && ./build.assets/build-test-compat.sh
