# This workflow will run everytime a PR is merged into master and attempt
# to update all open PRs that are out of date with master and have "Auto Merge"
# enabled to mimic the behavior of a merge queue.
name: "Merge Queue"
on:
  push:
    branches:
      - master

# Limit the permissions on the GitHub token for this workflow to the subset
# that is required. In this case, the merge queue needs to be able to write
# to Pull Requests (to update them), nothing else.
permissions:
  actions: none
  pull-requests: write
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  merge-queue:
    name: "Merge Queue"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout master branch"
        uses: "actions/checkout@v2"
        with:
          ref: "master"
      - name: "Installing the latest version of Go"
        uses: "actions/setup-go@v2"
      - name: "Update PRs"
        run: cd .github/workflows/robot && go run main.go -workflow=queue -token="${{ secrets.GITHUB_TOKEN }}" -reviewers="${{ secrets.reviewers }}"
