name: Build Teleport Connect
on: 
  push:
    branches:
      - tcsc/windows-gha-skunkworks
jobs:
  build:
    name: Build Teleport Connect

    runs-on: windows-2022

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v3
        with:
          path: teleport
          fetch-depth: 0

      - name: Checkout Webapps
        uses: actions/checkout@v3
        with:          
          repository: gravitational/webapps
          path: webapps

      - name: Checkout Webapps Enterprise
        uses: actions/checkout@v3
        with:          
          repository: gravitational/webapps.e
          path: webapps/e

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.1

      - name: Configure Node
        run: |
          npm config set msvs_version 2022
          corepack enable yarn

      - name: Build TSH
        working-directory: teleport
        env:
          GCO_ENABLED: 1
        run: |
          go build -o build/tsh.exe ./tool/tsh

      - name: Build Teleport Connect
        working-directory: webapps        
        run: |
          yarn install --frozen-lockfile
          yarn build-term
          yarn package-term "-c.extraMetadata.version=${{ env.TELEPORT_VERSION }}"
